// <auto-generated />
using System;
using AvaliacaoMedGrupo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AvaliacaoMedGrupo.Migrations
{
    [DbContext(typeof(AvaliacaoDbContext))]
    [Migration("20260331202050_AdicionarSexoNaoEspecificado")]
    partial class AdicionarSexoNaoEspecificado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AvaliacaoMedGrupo.Entities.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<int>("SexoTipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SexoTipoId");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("AvaliacaoMedGrupo.Entities.SexoTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SexoTipos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Masculino"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Feminino"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Nao Especificado"
                        });
                });

            modelBuilder.Entity("AvaliacaoMedGrupo.Entities.Contato", b =>
                {
                    b.HasOne("AvaliacaoMedGrupo.Entities.SexoTipo", "SexoTipo")
                        .WithMany()
                        .HasForeignKey("SexoTipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SexoTipo");
                });
#pragma warning restore 612, 618
        }
    }
}
